### ISSUE TITLE
CreateTransaction: should return an error message if TX nonce is lower than account nonce

### ISSUE THREAD

**Issue by mickys** [Zilliqa/kaya#52]
CreateTransaction: should return an error message if TX nonce is lower than account nonce

Fix: return Error Object instead of just the message.

## Details:
Call
```
getNonce( 0x17f343a7A13BaC8026D6C84e2Ee2925aEba1FA61 ) {
  balance: 88130, nonce: 17 
}

{ jsonrpc: '2.0',
  method: 'CreateTransaction',
  params:
   [ { version: 0,
       nonce: 1,
       to: '22537dfddb1232be8ce10c7fc4b784f61a4375a9',
       amount: <BN: 1>,
       pubKey: '03b51541a4e231517740ec9bc5dda5647bc5ef560f849f95a4f7d9eaa118fba131',
       gasPrice: 10,
       gasLimit: 10,
       code: '',
       data: '',
       signature: '9acfcb4a0aac7911559038c576cdbc0256a8ffe355c10d9922069ca3c7513806dfa32f01e00ed12bbf0012ec26e684c1015a71fc9352d9513f4b81d4179df8d6' } ],
  id: 31 }
```

EXPECTED:
```
new Error( "the tx doesn't have the correct nonce" );
```

Actual
```
{
status: 200,
statusText: 'OK',
config: {
     data: '{"jsonrpc":"2.0","method":"CreateTransaction","params":[{"version":0,"nonce":1,"to":"22537dfddb1232be8ce10c7fc4b784f61a4375a9","amount":"1","pubKey":"03b51541a4e231517740ec9bc5dda5647bc5ef560f849f95a4f7d9eaa118fba131","gasPrice":10,"gasLimit":10,"code":"","data":"","signature":"9acfcb4a0aac7911559038c576cdbc0256a8ffe355c10d9922069ca3c7513806dfa32f01e00ed12bbf0012ec26e684c1015a71fc9352d9513f4b81d4179df8d6"}],"id":29}' },
=>>> data: { id: 29, jsonrpc: '2.0', result: { Error: 'Invalid Tx Json' } } }
```

**Comment by edisonljh** [comment]
As the shards are now responsible for checking nonce and balance, the lookup node will no longer be checking the tx nonce and balance. Currently, the blockchain will return a transaction hash. But if the nonce is incorrect, the transaction will be ignored by the shard. Even though the lookup node (or kaya RPC in this case) returns a transaction hash, the transaction hash is not confirmed.

I have since fixed it in the commit 0fb529f2bcb8cabe34c3b2aa57b5a2f1b8914913. As seen, the transaction will only be logged if it is processed by the "blockchain" (i.e. passes balance checks).

Source: https://github.com/Zilliqa/Zilliqa/blob/master/src/libServer/Server.cpp
